// export * from './AlertsDemo';
// export * from './BadgeDemo';
// export * from './ButtonsDemo';
// export * from './CardDemo';
// export * from './IconsDemo';
// export * from './ListDemo';
// export * from './MainMenu';
// export * from './ModalDemo';
// export * from './RangeDemo';
// export * from './ToggleDemo';
// export * from './ToolbarDemo';
// export * from './TypographyDemo';

import AlertsDemo from './AlertsDemo';
import BadgeDemo from './BadgeDemo';
import ButtonsDemo from './ButtonsDemo';
import CardDemo from './CardDemo';
import IconsDemo from './IconsDemo';
import ListDemo from './ListDemo';
import MainMenu from './MainMenu';
import ModalDemo from './ModalDemo';
import RangeDemo from './RangeDemo';
import ToggleDemo from './ToggleDemo';
import ToolbarDemo from './ToolbarDemo';
import TypographyDemo from './TypographyDemo';

export { AlertsDemo };
export { BadgeDemo };
export { ButtonsDemo };
export { CardDemo };
export { IconsDemo };
export { ListDemo };
export { MainMenu };
export { ModalDemo };
export { RangeDemo };
export { ToggleDemo };
export { ToolbarDemo };
export { TypographyDemo };
